// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "TimeService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::whattime;

class TimeServiceHandler : virtual public TimeServiceIf {
 public:
  TimeServiceHandler() {
    // Your initialization goes here
  }

  int32_t TellMeTiime() {
    // Your implementation goes here
    printf("TellMeTiime\n");
    time_t now_time = time(NULL);
    return now_time;
  }

};

int main(int argc, char **argv) {
  int port = 29090;
  ::apache::thrift::stdcxx::shared_ptr<TimeServiceHandler> handler(new TimeServiceHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new TimeServiceProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

