/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TimeService_H
#define TimeService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "WhatTime_types.h"

namespace whattime {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class TimeServiceIf {
 public:
  virtual ~TimeServiceIf() {}
  virtual int32_t TellMeTiime() = 0;
};

class TimeServiceIfFactory {
 public:
  typedef TimeServiceIf Handler;

  virtual ~TimeServiceIfFactory() {}

  virtual TimeServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TimeServiceIf* /* handler */) = 0;
};

class TimeServiceIfSingletonFactory : virtual public TimeServiceIfFactory {
 public:
  TimeServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<TimeServiceIf>& iface) : iface_(iface) {}
  virtual ~TimeServiceIfSingletonFactory() {}

  virtual TimeServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TimeServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<TimeServiceIf> iface_;
};

class TimeServiceNull : virtual public TimeServiceIf {
 public:
  virtual ~TimeServiceNull() {}
  int32_t TellMeTiime() {
    int32_t _return = 0;
    return _return;
  }
};


class TimeService_TellMeTiime_args {
 public:

  TimeService_TellMeTiime_args(const TimeService_TellMeTiime_args&);
  TimeService_TellMeTiime_args& operator=(const TimeService_TellMeTiime_args&);
  TimeService_TellMeTiime_args() {
  }

  virtual ~TimeService_TellMeTiime_args() throw();

  bool operator == (const TimeService_TellMeTiime_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const TimeService_TellMeTiime_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimeService_TellMeTiime_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TimeService_TellMeTiime_pargs {
 public:


  virtual ~TimeService_TellMeTiime_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TimeService_TellMeTiime_result__isset {
  _TimeService_TellMeTiime_result__isset() : success(false) {}
  bool success :1;
} _TimeService_TellMeTiime_result__isset;

class TimeService_TellMeTiime_result {
 public:

  TimeService_TellMeTiime_result(const TimeService_TellMeTiime_result&);
  TimeService_TellMeTiime_result& operator=(const TimeService_TellMeTiime_result&);
  TimeService_TellMeTiime_result() : success(0) {
  }

  virtual ~TimeService_TellMeTiime_result() throw();
  int32_t success;

  _TimeService_TellMeTiime_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const TimeService_TellMeTiime_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TimeService_TellMeTiime_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimeService_TellMeTiime_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TimeService_TellMeTiime_presult__isset {
  _TimeService_TellMeTiime_presult__isset() : success(false) {}
  bool success :1;
} _TimeService_TellMeTiime_presult__isset;

class TimeService_TellMeTiime_presult {
 public:


  virtual ~TimeService_TellMeTiime_presult() throw();
  int32_t* success;

  _TimeService_TellMeTiime_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class TimeServiceClient : virtual public TimeServiceIf {
 public:
  TimeServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TimeServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t TellMeTiime();
  void send_TellMeTiime();
  int32_t recv_TellMeTiime();
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TimeServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<TimeServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TimeServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_TellMeTiime(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TimeServiceProcessor(::apache::thrift::stdcxx::shared_ptr<TimeServiceIf> iface) :
    iface_(iface) {
    processMap_["TellMeTiime"] = &TimeServiceProcessor::process_TellMeTiime;
  }

  virtual ~TimeServiceProcessor() {}
};

class TimeServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TimeServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< TimeServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< TimeServiceIfFactory > handlerFactory_;
};

class TimeServiceMultiface : virtual public TimeServiceIf {
 public:
  TimeServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<TimeServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TimeServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<TimeServiceIf> > ifaces_;
  TimeServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<TimeServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t TellMeTiime() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->TellMeTiime();
    }
    return ifaces_[i]->TellMeTiime();
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class TimeServiceConcurrentClient : virtual public TimeServiceIf {
 public:
  TimeServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TimeServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t TellMeTiime();
  int32_t send_TellMeTiime();
  int32_t recv_TellMeTiime(const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
