/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "WhatTime_constants.h"

namespace whattime {

const WhatTimeConstants g_WhatTime_constants;

WhatTimeConstants::WhatTimeConstants() {
}

} // namespace

