/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef WhatTime_CONSTANTS_H
#define WhatTime_CONSTANTS_H

#include "WhatTime_types.h"

namespace whattime {

class WhatTimeConstants {
 public:
  WhatTimeConstants();

};

extern const WhatTimeConstants g_WhatTime_constants;

} // namespace

#endif
